version: '3.4'

services:
  backend:
    build:
      context: ./backend
      target: dev
    image: knuffon-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
  frontend:
    build:
      context: ./frontend
    image: knuffon-frontend
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/code
